### PR TITLE
fix: ignore single css chunk (close #688)

### LINKED ISSUE #688: LoadableReady not be called if required chunks have a chunk only contains css.
## 🐛 Bug Report

If webpack generates a chunk only contains css file, no js, loadable ready check will fail, and callback function not be called.

https://github.com/gregberge/loadable-components/blob/dde2252136a2d7f3ff635f85deff429948130883/packages/component/src/loadableReady.js#L56-L67

## To Reproduce

create a new react webpack project, just simple import css in components, add `mini-css-extract-plugin` to webpack config, insure pack a chunk only contains css file.

## Expected behavior

Filter out the chunk only contains css file when generating `RequiredChunksScriptTag`:

https://github.com/gregberge/loadable-components/blob/dde2252136a2d7f3ff635f85deff429948130883/packages/server/src/ChunkExtractor.js#L282-L284

Issues without a reproduction link are likely to stall.

## Run `npx envinfo --system --binaries --npmPackages @loadable/component,@loadable/server,@loadable/webpack-plugin,@loadable/babel-plugin --markdown --clipboard`

Paste the results here:

```bash
## System:
 - OS: macOS 11.0.1
 - CPU: (8) x64 Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz
 - Memory: 1.62 GB / 16.00 GB
 - Shell: 5.8 - /bin/zsh
## Binaries:
 - Node: 14.15.2 - /var/folders/9t/xn8r9ffn31z6vnk1vmfdzcd00000gn/T/fnm_multishell_25701_1610416859901/bin/node
 - Yarn: 1.22.10 - /usr/local/bin/yarn
 - npm: 6.14.9 - /var/folders/9t/xn8r9ffn31z6vnk1vmfdzcd00000gn/T/fnm_multishell_25701_1610416859901/bin/npm
## npmPackages:
 - @loadable/babel-plugin: ^5.13.2 => 5.13.2 
 - @loadable/component: ^5.14.1 => 5.14.1 
 - @loadable/server: ^5.14.0 => 5.14.0 
 - @loadable/webpack-plugin: ^5.14.0 => 5.14.0
```

### PR DESCRIPTION
**Pull request by jas0ncn**
## Summary

Ignore single css chunk when `RequiredChunks` added into HTML output during SSR. 

Issue: https://github.com/gregberge/loadable-components/issues/688

### CODE REVIEW

**Comment by theKashey** [comment]
There is just single one issue with test preventing merging this PR to a master branch 😭

File: packages/server/src/ChunkExtractor.js [hunk 1]
```diff
@@ -171,6 +171,11 @@ function isValidChunkAsset(chunkAsset) {
   return chunkAsset.scriptType && !HOT_UPDATE_REGEXP.test(chunkAsset.filename)
 }
 
+const CSS_FILE = /\.css$/
```
Comment (cahnory) [inline packages/server/src/ChunkExtractor.js:174]: Rather than testing if all files are CSS, shouldn't it be tested if at least one file is JavaScript?

**Comment by jas0ncn** [comment]
> There is just single one issue with test preventing merging this PR to a master branch 😭

Should I generate new `__fixtures__` folder to test this case, or just modify `stats.json` directly? This case needs webpack5 and I think maybe shouldn't update the server-side-rendering example to webpack5.

File: packages/server/src/ChunkExtractor.js (hunk 1 above)
Comment (jas0ncn) [reply packages/server/src/ChunkExtractor.js:174]: Right, I will modify Regexp and test js.

**Comment by cahnory** [comment]
> > There is just single one issue with test preventing merging this PR to a master branch 😭
> 
> Should I generate new `__fixtures__` folder to test this case, or just modify `stats.json` directly? This case needs webpack5 and I think maybe I shouldn't update webpack to v5 of the server-side-rendering example.

Not sure if it's the right answer but in my (now closed 😢) I chose to modify the fixtures:
https://github.com/gregberge/loadable-components/pull/655/files#diff-7979dacf4945ebda3d5b355e934617b7bf14dbe6ec1996030bce2d413503349a

I think if your code is working but not passing the tests, it's better to edit tests if possible (tests adapt to code, not the other way).

**Comment by theKashey** [comment]
merging to continue development from my side...

**Comment by theKashey** [comment]
> Should I generate new __fixtures__ folder to test this case, or just modify stats.json directly? 

fixtures should be always generated from some source code, but look like that moment got lost somewhere.
After regenerating status from the expected source(examples/server-side-rendering) I have 18 broken tests....

**Comment by theKashey** [comment]
While there is no test yet for this use case, it will be very good to double check that current version in master works and/or modify https://github.com/gregberge/loadable-components/tree/master/examples/server-side-rendering to produce the _extended_ stats.
👉there is yet undocumented script `scripts/prepare` to do perform this operation.
